#!/usr/bin/env bash
# Summary: Install a version of Go.
#
# Usage: goenv install <version>
#
# Versions should be in the form of N.N.N

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$GOENV_DEBUG" ] && {
  set -x
}

# Pull the desired version out of ARGV
version="$1"
version_dir="$GOENV_ROOT/versions/$version"

# stash the pwd
OLDPWD=$(pwd)

# Make the version dir and get in there
mkdir -p "$version_dir"
cd "$version_dir"

platform="$(uname -s | tr '[:upper:]' '[:lower:]')"

if [ "$(uname -m)" = "x86_64" ]; then
  arch="amd64"
else
  arch="386"
fi

if [ "$platform" = "darwin" ]; then
  # Since go version 1.2, osx packages were subdivided into 10.6 and 10.8
  if [ "$version" = "1.2" -o "$version" \> "1.2" -a "$version" \< "1.5" ]; then
    if [ "$(uname -r)" \> "12" ]; then
      extra="-osx10.8"
    else
      extra="-osx10.6"
    fi
  fi
fi

# Since go version 1.2, download binary location has been changed to http://golang.org/
# has been changed to https://storage.googleapis.com/golang/
# https://qiita.com/akegashi/items/35bde2af80682ca77a70#%E8%BF%BD%E8%A8%982017117
NUMVERSION=$(echo "$version"|awk -F. '{printf "%d%02d%02d", $1, $2, $3}')
if [ "$NUMVERSION" -ge 10200 ]; then
  download="https://storage.googleapis.com/golang/go${version}.${platform}-${arch}${extra}.tar.gz"
else
  download="https://go.googlecode.com/files/go${version}.${platform}-${arch}${extra}.tar.gz"
fi

# Can't get too clever here
set +e

# Download binary tarball and install
# Linux downloads are formatted differently from OS X
# curl -k option added 
(
  curl -Lk -s -f "$download" > "/tmp/go${version}.${platform}-${arch}.tar.gz" && \
  tar zxvf "/tmp/go${version}.${platform}-${arch}.tar.gz" --strip-components 1 && \
  rm "/tmp/go${version}.${platform}-${arch}.tar.gz"
) || \
  {
    cd $OLDPWD
    rmdir "$version_dir"

    echo "goenv: unable to install Go \`${version}' from binary, download not available from $download"
    exit 1
  }

echo "Installed ${version}"
cd $OLDPWD

exec "${GOENV_ROOT}/bin/goenv" rehash
